const ActionTypes = {
   PRODUCTS_LOADED: "PRODUCTS_LOADED",
   CART_LOADED: "CART_LOADED",
   ITEM_ADDED_TO_CART: "ITEM_ADDED_TO_CART",
   ITEM_REMOVED_FROM_CART: "ITEM_REMOVED_FROM_CART",
   ITEM_QUANTITY_INCREASED: "ITEM_QUANTITY_INCREASED",
   ITEM_QUANTITY_DECREASED: "ITEM_QUANTITY_DECREASED",
   LOGGED_IN: "LOGGED_IN",
   LOGGED_OUT: "LOGGED_OUT",
   USER_DETAILS: "USER_DETAILS",
   ORDER_PLACED: "ORDER_PLACED"
}

export default ActionTypes